Added more to the devstart function of the shell script to bring up my development environment

diff --git a/bin/godev b/bin/godev
--- a/bin/godev
+++ b/bin/godev
@@ -6,23 +6,33 @@
 #set -x verbose #echo on
 
 workspace="/f/dev/work"
-subwork="$1"
+project="$1"
 ansible="$workspace/ansible"
 ansible_git="https://github.com/ansible/ansible.git"
-dot_files="$workspace/vmifiles/$subwork"
-ERR=0
+dot_files="$workspace/vmifiles/$project"
 
+#======================================================================
+#
+#   devstart
+#
+#   Starts up the development vm, setting up vagrant with what'set
+#     necessary to provision by Ansible
+#
 devstart()
 {
   echo "====================================="
   echo "=  RoR Development in a VM: STARTUP"
   echo "====================================="
   echo "= Worskpace: [$workspace]"
-  echo "= Machine: [$subwork]"
+  echo "= Machine: [$project]"
   echo "= "
   
   # only the bare necessities to get to Ansible setting everything update
 
+  #----------------------------------------------
+  #  Prepare for Vagrant
+  #
+  
   echo "Getting situated."
 
   cd $workspace
@@ -31,39 +41,87 @@ devstart()
 
   vagrant plugin update vagrant-vbguest
 
-  if [ ! -d "$subwork" ]; then
-    mkdir $subwork
-    cd $subwork
-    # check out git files
-    
-  else
-    cd $subwork
-    #vagrant halt  
+  if [ ! -d "$project" ]; then
+    mkdir $project
+    # TODO:  git clone files    
   fi
+
+  cd $project
+
+  # check if vagrant initialized
+  if [ ! -f "Vagrantfile" ] then
+    vagrant init
+  fi
+  
+  if [ $? ne 0 ] then
+    echo "...........GODEV ERROR: vagrant init failed."  
+    exit 3
+  fi
+
+  #----------------------------------------------
+  #  Update the vagrant and provision files
+  #  from the git repository
+  
+  # TODO: if no git, clone;
+  # TODO: otherwise, update
+  
+  
+  
 }
 
+#======================================================================
+#
+#   devstop
+#
+#   Stops the development vm and cleans up, ready for host machine
+#     shutdown
+#
 devstop()
 {
   echo "====================================="
   echo "=  STOP"
   echo "====================================="
   echo "= Worskpace: $workspace"
-  echo "= Machine: $subwork"
+  echo "= Machine: $project"
   echo "= "
   
-  cd $workspace/$subwork
+  cd $workspace/$project
   #vagrant halt
   #copy changed dotfiles back to local repo
   #commit local repo
 }
 
-echo ".......[$1]..........[$2]................"
+#======================================================================
+#
+#   Shell script's main body
+#
+
+#----------------------------------------------
+#   Validate inputs
+#
+workspace="/f/dev/work"
+project="$1"
+ansible="$workspace/ansible"
+ansible_git="https://github.com/ansible/ansible.git"
+dot_files="$workspace/vmfiles/$project"
+
+echo "...........GODEV:  1=[$1] 2=[$2]"
+echo "...........GODEV:  workspace=$workspace"
+echo "...........GODEV:  project=$project"
+echo "...........GODEV:  ansible=$ansible"
+echo "...........GODEV:  ansible_git=$ansible_git"
+echo "...........GODEV:  dot_files=$dot_files"
 echo ""
 
 if [ -z "$1" ]; then
-  echo "ERROR: no project given."
+  echo "...........GODEV ERROR: no project given."
   exit 1
 fi
+
+#----------------------------------------------
+#
+#  start or stop development environment
+#
 
 if [ "$2" = "stop" ]; then
   devstop
